### PR TITLE
for qbcore shared.lua

### PR DESCRIPTION
**Pull request by ItzMuri**

### CODE REVIEW

**Comment by PLOKMJNB** [comment]
Hi and Thanks for the PR!

I'll be checking this out soon. Also let me know your Discord handle so I can add you to the contributors list and give you the contributor role in the discord.

**Comment by PLOKMJNB** [comment]
Resolution for https://github.com/PLOKMJNB/FiveM-Civ-Car-Pack/issues/89

**Comment by ItzMuri** [comment]
#89 is outdated

**Review by Red-Killer — APPROVED** [review]

**Comment by Red-Killer** [comment]
@PLOKMJNB maybe you want to move the shared.lua into the Framework Files folder looks better

**Comment by PLOKMJNB** [comment]
Yeah, I'll add that to my to-do list.

**Pull request merged**
